### ISSUE TITLE
Automation

### ISSUE THREAD

**Issue by Madis0** [JustAPotota/fabric-xaero-warps#4]
I though the mod worked automatically when a player types /claimlist, but it wasn't the case for me - had to type /cp worlds and /cp add worldname. Any plans to make it more seamless? 

Maybe regex-ing _everything_ wouldn't be the best idea, but observing the chat right after /claimlist is typed could work.

**Comment by JustAPotota** [comment]
As it says in the description, this is a very specific mod for showing EssentialsX warps as Xaero waypoints. I don't know what plugin you're using for claims, but I don't plan on supporting it at this time.

**Comment by Madis0** [comment]
Sorry, wrong mod.
